print("hello world")
print("this is batch 1 of FYCS foss practicle")
print("review of the code")
print("revision on pull request command")
print("hello world")
print("this is batch 1 of FYCS foss practicle")
print("review of the code")
print("revision on pull request command")
